# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: train
    chdir: true
  run:
    dir: output/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - dir: local
  - model: mlp

n_folds: 5
fold: 0
n_epochs: 8
train_batch_size: 4096
valid_batch_size: 4096
scheduler: "CosineAnnealingLR"
lr: 5e-4
min_lr: 1e-6
T_max: 500
n_accumulates: 1

