# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: train
    chdir: true
  run:
    dir: output/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - dir: local

seed: 42

num_epochs: 50
train_batch_size: 8192
valid_batch_size: 8192
lr: 1e-4
num_accumulates: 1
early_stopping_steps: 2
